### ISSUE TITLE
Extensions on BuildContext causes issues with generated widgets

### ISSUE THREAD

**Issue by Aidanvii7** [rrousselGit/functional_widget#58]
### Steps to reproduce
1. Create a new application with the default template flutter create example
2. Add functional_widget and functional_widget_annotation to pubspec.yaml
3. Ensure SDK is at least 2.6.0 to make use of extension methods
```
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.5.1

builders:
  functional_widget: ^0.7.1
```
4. Create an extension on `BuildContext` (no actual extension methods are required):
```
extension on BuildContext {

}
```
5. Create a functional widget that recieves it's `BuildContext` such as:
```
@widget
Widget example(BuildContext context) => const Placeholder();
```
6. Import the extension
### Expected source generated:
```
class Example extends StatelessWidget {
  const Example({Key key}) : super(key: key);

  @override
  Widget build(BuildContext _context) => example(_context);
}
```
### Actual source generated:
```
class Example extends StatelessWidget {
  const Example(this.context, {Key key}) : super(key: key);

  final dynamic context;

  @override
  Widget build(BuildContext _context) => example(context);
}
```
