### ISSUE TITLE
Version conflict due to build_config

### ISSUE THREAD

**Issue by lekz112** [rrousselGit/functional_widget#72]
Hello, I am trying to start using this library, but keep getting the following error:
```
generating build script...
Because build_runner >=1.6.5 <1.7.4 depends on build_config >=0.4.1 <0.4.2 and functional_widget >=0.7.3 depends on build_config ^0.4.2, build_runner >=1.6.5 <1.7.4 is incompatible with functional_widget >=0.7.3.
So, because flutter_tool depends on both functional_widget ^0.7.3 and build_runner 1.7.1, version solving failed.
generating build script...                                          2.0s
Exception: pub get failed (1; So, because flutter_tool depends on both functional_widget ^0.7.3 and build_runner 1.7.1, version solving failed.)
Exited (1)
```

It seems that some dependency of `flutter_tool` pulls a fixed version of `build_runner`, which depends on an old `build_config` version.

Here is my `pubspec.yaml`:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_maps_flutter: ^0.5.28+1
  functional_widget_annotation: ^0.5.1
  geolocator: ^5.3.2+2
  rxdart: ^0.24.1
  flutter:
    sdk: flutter
  openapi:
    path: gen

builders:
  functional_widget: ^0.7.3
```
I am using latest stable version of Flutter:
```
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (5 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

What I have already tried:
1. Using `dependency_override` for `build_runner` or `build_config` - doesn't seem work.
2. Using `master` branch of Flutter SDK - same behavior.
3. Adding `build_runner: 1.9.0` to `flutter_tool` - breaks the package.

Any ideas how to make it work?
